title: Civic Tech Toolkit
email: jordan@addwonder.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "civic-tech-toolkit"
url: ""

include: ["_pages"]
exclude: ["hold", "readme.md"]

permalink: pretty

collections:
  resources:
    output: true
    permalink: /resources/:path/
  case-studies:
    output: true
    permalink: /case-studies/:path/

defaults:
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
  - scope:
      path: ""
      type: case-studies
    values:
      layout: case-study

# plugins:

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
